//
//  bootstrap.c
//  electra
//
//  Created by Jamie Bishop on 11/02/2018.
//  Copyright © 2018 Electra Team. All rights reserved.
//

#include "bootstrap.h"
#include "utilities/file_utils.h"
#include "fun_objc.h"
#include "utilities/amfi_utils.h"
#include "utilities/utils.h"
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <spawn.h>

#define tar "/electra/tar"

pid_t pd;

void copy_tar() {
    extractGz("tar", "/electra/tar");
    chmod(tar, 0755);
    inject_trusts(1, (const char **)&(const char*[]){tar});
}

void copy_basebinaries() {
    mkdir("/electra", 0755);
    
    copy_tar();
    
    // Remove old base binaries
    unlink("/electra/inject_amfid");
    unlink("/electra/inject_launchd");
    unlink("/electra/launchd_payload.dylib");
    unlink("/electra/xpcproxy_payload.dylib");
    
    unlink("/electra/inject_ctriticald");
    unlink("/electra/pspawn_payload.dylib");
    
    unlink("/electra/amfid_payload.dylib");
    unlink("/electra/launchjailbreak");
    unlink("/electra/jailbreakd");
    
    extractGz("rm","/electra/rm");
    chmod("/electra/rm", 0755);
    
    posix_spawn(&pd, tar, NULL, NULL, (char **)&(const char*[]){ tar, "-xpf", progname("basebinaries.tar"), "-C", "/electra", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    printf("[bootstrapper] copied the required binaries into the right places\n");
    
    inject_trusts(4, (const char **)&(const char*[]){
        "/electra/inject_criticald",
        "/electra/amfid_payload.dylib",
        "/electra/pspawn_payload.dylib",
        "/electra/libjailbreak.dylib"
    });
}

void extract_bootstrap() {
    unlink("/bin/launchctl");
    extractGz("launchctl", "/electra/launchctl");
    cp("/bin/launchctl", "/electra/launchctl");
    chmod("/bin/launchctl", 0755);
    unlink("/electra/launchctl");

    
    installingCydia();
    
    ////bin folder files cleanup
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bash", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bunzip2", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bzcat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bzip2", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bzip2recover", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bzip2_64", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/cat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/chgrp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/chmod", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/chown", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/cp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/date", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/dd", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/dir", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/echo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/egrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/false", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/fgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/grep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/gzip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/gtar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/gunzip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/gzexe", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/hostname", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/ln", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/ls", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/jtoold", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/kill", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/mkdir", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/mknod", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/mv", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/mktemp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/pwd", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/rm", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/readlink", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/rmdir", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/run-parts", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/su", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/sync", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/stty", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/sh", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/sleep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/sed", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/tar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/touch", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/true", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/uname", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/vdr", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/vdir", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/uncompress", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/znew", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zegrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zmore", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zdiff", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zcat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zcmp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zfgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zforce", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zless", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/zgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    
    
    ////etc folder cleanup
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/dropbear", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/default", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/ssh", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/zshrc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/alternatives", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/etc/pam.d", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    ///////private/etc
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/default", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/ssh", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/ssl", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/profile", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/etc/profile.d", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    
    //////sbin folder files cleanup
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/dmesg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/halt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/dynamic_pager", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/nologin", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/cat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/zshrc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    //////var folder cleanup
    ////private/var
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/backups", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/cache", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/Ext3nder-Installer", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/lib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/local", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/lock", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/spool", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/lib/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/lib/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/lib/cydia", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/cache/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/db/stash", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/stash", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/tweak", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/mobile/Library/Fingal", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/var/mobile/Library/Filza", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/private/var/run/utmp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    unlink("/bin/bash");
    unlink("/authorize.sh");
    unlink("/etc/motd");
    unlink("/.cydia_no_stash");
    
    ////////usr files and folder
    ////usr/share files
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/share/bigboss", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/share/dict", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/share/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/share/gnupg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/share/tabset", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/share/terminfo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    ////usr/include files
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/include", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    ////usr/sbin files
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/start-start-daemon", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/accton", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/vifs", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/ac", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/update", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/pwd_mkdb", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/sysctl", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/zdump", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/startupfiletool", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/iostat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/mkfile", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/zic", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/vipw", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    
    ////usr/local files
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/local/bin", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    ////usr/libexec files
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/cydia", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/gnupg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/gpg*", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/gpg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    //posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/gpg*", NULL }, NULL);
    //waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/frcode", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/bigram", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/code", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/reload", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/rmt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/filza", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/_rocketd_reenable", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/rocketd", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/MSUnrestrictProcess", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/libexec/substrate", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    ////usr/lib files
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/TweakInject", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/TweakInject.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapplist.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libflipswitch.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-inst.2.0.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-inst.2.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-pkg.5.0.1.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-pkg.5.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-private.0.0.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-private.0.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libassuan.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libassuan.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libassuan.la", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libnpth.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libnpth.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libnpth.la", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libgpg-error.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libgpg-error.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libgpg-error.la", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libksba.8.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libksba.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libksba.la", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/pam", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/pkgconfig", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/cycript0.9", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    unlink("/usr/lib/libsubstitute.0.dylib");
    unlink("/usr/lib/libsubstitute.dylib");
    unlink("/usr/lib/libsubstrate.dylib");
    unlink("/usr/lib/libjailbreak.dylib");
    unlink("/usr/bin/recache");
    unlink("/usr/bin/killall");
    unlink("/usr/share/terminfo");
    unlink("/usr/libexec/sftp-server");
    unlink("/usr/lib/SBInject.dylib");
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/SBInject", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/SBInject.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhistory.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-pkg.dylib.4.6", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpam.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpamc.1.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpackageinfo.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/librocketbootstrap.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-pkg.dylib.4.6.0", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpanelw.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhistory.5.2.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libreadline.6.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpanel.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-inst.dylib.1.1", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcurses.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/liblzmadec.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhistory.6.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libformw.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libncursesw.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-inst.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libncurses.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-pkg.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libreadline.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhistory.6.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libform.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpanelw.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libmenuw.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libform.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/terminfo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpam.1.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libmenu.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpatcyh.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libreadline.6.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/liblzmadec.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libncurses.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhistory.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpamc.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libformw.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-inst.dylib.1.1.0", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpanel.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/liblzmadec.0.0.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/_ncurses", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpam_misc.1.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libreadline.5.2.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpam_misc.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libreadline.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libmenuw.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libpam.1.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libmenu.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/liblzmadec.la", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libncursesw.5.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcycript.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcycript.jar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-inst.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libapt-pkg.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libdpkg.a", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcrypto.1.0.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libssl.1.0.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcycript.db", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcurl.4.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcycript.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcycript.cy", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libdpkg.la", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libsubstrate.0.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/ssl", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/bash", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/coreutils", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/engines", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/p7zip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/Cephei.framework", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/CepheiPrefs.framework", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcephei.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libcepheiprefs.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhbangcommon.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/lib/libhbangprefs.dylib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    /////usr/bin files folders cleanup
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/[", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzmainfo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/asu_inject", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/iomfsetgamma", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/chsh", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgv", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/toe", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cmp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/locate", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cfversion", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg-zip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dselect", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/defaults", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/infotocap", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ncursesw5-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-deb", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/diff3", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sw_vers", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/df", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/renice", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/captoinfo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-name", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/bashbug", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-split", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/chfn", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tset", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unlzma", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/reset", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/pagesize", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgsplit", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/diff", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/uiopen", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-trigger", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/updatedb", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ncurses5-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/script", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ldrestart", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/time", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sbdidlaunch", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/clear", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tic", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/getconf", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzless", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-query", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/infocmp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzcmp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/arch", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xargs", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/getty", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzcat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ldid", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/uiduid", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dirname", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzdiff", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/find", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzmadec", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sdiff", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzmore", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tput", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzfgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/hostinfo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzma", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sbreload", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/login", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/which", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gssc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-key", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/lzegrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/passwd", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gtar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dselect", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cycc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-statoverride", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-deb", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-divert", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cynject", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/update-alternatives", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-split", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-trigger", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-maintscript-helper", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/env", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gnutar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cycript", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-query", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    //from a-z cleanup usr/bin
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-cache", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-cdrom", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-extracttemplates", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-ftparchive", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-mark", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-sortpkgs", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/apt-get", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/b2sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/base32", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/base64", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/basename", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/icleaner.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/c_rehash", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/chcon", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/chown", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/chroot", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cksum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/comm", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/com.julioverne.ext3nder-installer", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/csplit", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/curl", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/curl-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/cut", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_archive", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_checkpoint", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_deadlock", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_dump", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_hotbackup", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_load", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_log_verify", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_printlog", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_recover", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_replicate", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_sql_codegen", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_stat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_tuner", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_upgrade", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/db_verify", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dbclient", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dbsql", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/debugserver", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dircolors", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dirmngr", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dirmngr-client", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-architecture", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-buildflags", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-buildpackage", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-checkbuilddeps", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-distaddfile", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-genbuildinfo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-genchanges", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-gencontrol", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-gensymbols", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-mergechangelogs", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-parsechangelog", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-scanpackages", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-scansources", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-shlibdeps", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-source", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dpkg-vendor", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/du", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/dumpsexp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/expand", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/expr", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/factor", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/filemon", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/fmt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/fold", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/funzip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg-agent", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg-connect-agent", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg-error", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg-error-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpg2", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgconf", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgparsemail", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgscm", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgsm", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgtar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/gpgv2", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/groups", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/head", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/hmac256", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/hostid", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/id", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/install", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/join", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/jtool", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/kbxutil", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/killall", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ksba-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/less", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/libassuan-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/libgcrypt-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/link", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/logname", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/md5sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/mkfifo", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/mktemp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/more", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/mpicalc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/nano", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/nice", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/nl", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/nohup", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/nproc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/npth-config", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/numfmt", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/od", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/openssl", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/paste", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/pathchk", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/pincrush", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/pinky", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/plconvert", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/pr", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/printenv", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/printf", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/procexp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ptx", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/realpath", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/recache", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/rnano", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/runcon", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/seq", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sftp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sha1sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sha224sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sha256sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sha384sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sha512sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/shred", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/shuf", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sort", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/split", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ssh", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ssh-add", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ssh-agent", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ssh-keygen", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/ssh-keyscan", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/stat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/stdbuf", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sum", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/sync", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tabs", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tac", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tail", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tee", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/test", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/timeout", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tr", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/truncate", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tsort", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/tty", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unexpand", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/uniq", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unlink", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unzip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unzipsfx", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unxz", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/unrar", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/uptime", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/users", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/watchgnupg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/wc", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/wget", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/who", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/whoami", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xz", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzcat", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzcmp", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzdec", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzdiff", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzegrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzfgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzgrep", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzless", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/xzmore", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/yes", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/zip", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/zipcloak", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/zipnote", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/zipsplit", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/7z", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/7za", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    
    ////usr/local files and folders cleanup
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/local/bin", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/local/lib/libluajit.a", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/local/lib", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    unlink("/bin/zsh");
    unlink("/etc/profile");
    unlink("/etc/zshrc");
    unlink("/usr/bin/scp");
    
    ///////Applications cleanup
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/Activator.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/Anemone.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/Cydia.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/Cylinder.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/iCleaner.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/BarrelSettings.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/Ext3nder.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/Filza.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/GBA4iOS.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/jjjj.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/SafeMode.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/AppCake.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/NewTerm.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/MobileTerminal.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/MTerminal.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/MovieBox3.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Applications/BobbyMovie.app", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    ////library folder files and subfolders
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Alkaline", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Activator", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Barrel", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/BarrelSettings", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Cylinder", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/dpkg", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Frameworks", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/LaunchDaemons", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/MobileSubstrate", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/PreferenceBundles", NULL },  NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/PreferenceLoader", NULL },  NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/SBInject", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Application Support/Snoverlay", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Application Support/Activator", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Application Support/Cylinder", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Application Support/Barrel", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Application Support/BarrelSettings", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/test_inject_springboard.cy", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Themes", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/TweakInject", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Zeppelin", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Flipswitch", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Library/Switches", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/System/Library/PreferenceBundles/AppList.bundle", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/System/Library/Themes", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bootstrap", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/Th0r", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/jb", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    
    posix_spawn(&pd, tar, NULL, NULL, (char **)&(const char*[]){ tar, "--preserve-permissions", "-xvf", progname("/3C.tar"), "-C", "/", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    unlink("/3C.tar");
    posix_spawn(&pd, "/usr/bin/uicache", NULL, NULL, (char **)&(const char*[]){ "uicache", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/uicache", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/games", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/bin/killall", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/usr/sbin/reboot", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/sbin/reboot", NULL }, NULL);
    waitpid(pd, NULL, 0);
    posix_spawn(&pd, "/electra/rm", NULL, NULL, (char **)&(const char*[]){ "rm", "-rf", "/bin/bash", NULL }, NULL);
    waitpid(pd, NULL, 0);
    
    unlink("/usr/libexec/cydia/move.sh");
    unlink("/.bootstrapped_electra");
    unlink("/.cydia_no_stash");
    unlink("/.bootstrapped_Th0r");
    unlink("/electra-prejailbreak");
    unlink("/electra/createSnapshot");
    
    printf("[bootstrapper] cleaned up jb files / \n");
    post_bootstrap(true);
}

void post_bootstrap(const bool runUICache) {
    pid_t pd;
    if (runUICache){
        posix_spawn(&pd, "/usr/bin/uicache", NULL, NULL, (char **)&(const char*[]){ "uicache", NULL }, NULL);
        waitpid(pd, NULL, 0);
    }
    
    unlink(tar);

    unlink("/usr/lib/libjailbreak.dylib");



    
    printf("[bootstrapper] device has been bootstrapped!\n");
    
    if (runUICache){
        cydiaDone();
    }
}

